DATA aa; 
do n = 2 to 100; 
alpha=0.05; 
mi1=21.8; 
mi2=26.4; 
stdev1=4.1; 
stdev2=5.9; 
df=2*n-2; 
sp = sqrt(((n-1)*stdev1*stdev1+(n-1)*stdev2*stdev2)/(n+n-2)); 
lambda=(abs(mi2-mi1)/sp)/sqrt(1/n+1/n); 
tcrit_low=TINV(alpha/2,df); 
tcrit_up=TINV(1-alpha/2,df); 
tcrit_one_tail=TINV(1-alpha,df); 
power_one_tail=1-CDF('t',tcrit_one_tail,df,lambda); 
power_two_tail=CDF('t',tcrit_low,df,lambda)+ 1-CDF('t',tcrit_up,df,lambda); 
OUTPUT; 
END; 
PROC PRINT DATA=aa (obs=1 ); 
TITLE 'one-tailed'; 
WHERE power_one_tail > .80; 
VAR alpha n df power_one_tail; 
RUN; 
PROC PRINT DATA=aa (obs=1 ); 
TITLE 'two-tailed'; 
WHERE power_two_tail > .80; 
VAR alpha n df power_two_tail; 
RUN;
